version: '2'

services:
  nginx:
    build: "./requirements/nginx"
    container_name: nginx
    restart: always
    volumes:
      - wp:/var/www/html
    ports:
      - "443:443"
    networks:
      - intra
  mariadb:
    build: "./requirements/mariadb"
    container_name: mariadb
    restart: always
    volumes:
      - db:/var/lib/mysql
    networks:
      - intra
    env_file:
      - ".env"
    expose:
      - "3306"
    tty: true
  wordpress:
    build: "./requirements/wordpress"
    container_name: wordpress
    restart: always
    volumes:
      - wp:/var/www/html
    networks:
      - intra
    env_file:
      - ".env"
    expose:
      - "9000"

networks:
  intra:
    driver: bridge

volumes:
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hyunlee/data/wp'
      # device: '/Users/hyunlee/Desktop/Inception/wp'
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/hyunlee/data/db'
      # device: '/Users/hyunlee/Desktop/Inception/db'
